project3/app_learning_logs/urls.py
"""Defines URL patterns for app_learning_logs"""

from django.urls import path
from . import views

app_name = 'app_learning_logs'
urlpatterns = [
    #Home page
    path('', views.index, name='index'),
    #Page that shows all topics.
    path('topics/', views.topics, name='topics'),
    #Detail page for single topic.
    path('topics/<int:topic_id>', views.topic, name='topic'),
    #Page for adding a new topic
    path('new_topic/', views.new_topic, name='new_topic'),
    #Page for adding a new entry
    path('new_entry/<int:topic_id>', views.new_entry, name='new_entry'),
]

project3/app_learning_logs/models.py
from django.db import models

# Create your models here.

class Topic(models.Model):
     """ A topic the user is learning about."""
     text = models.CharField( max_length = 200)
     date_added = models.DateTimeField( auto_now_add = True)
     
     def __str__(self): #This function will show the default field when you query the 'Topic' from database. Here it will return text.
        """ Return a string representation of the model.""" 
        return self.text

class Entry(models.Model):
   """Something specific learned about the topic."""
   topic = models.ForeignKey(Topic, on_delete=models.CASCADE) #This line means topic is attached with the ID of another record in DB (Topic) and Entries should be 
   #deleted when Topic is deleted. This is called cascading.
   text = models.TextField()
   date_added = models.DateTimeField(auto_now_add=True)

   class Meta: #This is a nested class, inside Entry class. Here we are telling django to use 'Entries' not 'Entrys' when calling 'Entry' class multiple times.
      verbose_name_plural = 'entries'

   def __str__(self):
      """Return a string representation of the model."""
      if len(self.text) >= 50:
         return(f"{self.text[:50]}...")
      else:
          return(f"{self.text[:]}")





 

project3/app_learning_logs/forms.py
from django import forms
from django.db.models import fields
from django.forms import widgets
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

project3/app_learning_logs/views.py
from django.shortcuts import render, redirect
from .models import Topic
from .forms import EntryForm, TopicForm

# Create your views here.

def index(request):
    """The home page for Learning Log."""
    return render(request, 'app_learning_logs/index.html')

def topics(request):
    """Show all topics."""
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'app_learning_logs/topics.html', context)

def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'app_learning_logs/topic.html', context)

def new_topic(request):
    """Add a new topic."""
    if request.method != 'POST':
        #No data submitted; create a blank form.
        form = TopicForm()
    else:
        #POST data submitted; process data
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('app_learning_logs:topics')

    #Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'app_learning_logs/new_topic.html', context)

def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        #No data submitted; create a blank form.
        form = EntryForm()
    else:
        #Post data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('app_learning_logs:topic', topic_id=topic_id)

    #Display a blank or invalid form.
    context = {'topic': topic, 'form': form}
    return render(request, 'app_learning_logs/new_entry.html', context)

project3/app_learning_logs/templates/app_learning_logs/base.html
<p>
    <a href="{% url 'app_learning_logs:index' %}">Learning Log</a> - 
    <a href="{% url 'app_learning_logs:topics' %}">Topics</a>
</p>
{% block content %}{% endblock content %}

project3/app_learning_logs/templates/app_learning_logs/index.html
{% extends 'app_learning_logs/base.html' %}

{% block content %}
  <p> Learning Log helps you keep track of your learning, for any topic you're learning about. </p>
{% endblock content %}

project3/app_learning_logs/templates/app_learning_logs/new_entry.html
{% extends 'app_learning_logs/base.html' %}

{% block content %}
  <p><a href ="{% url 'app_learning_logs:topic' topic.id %}">{{ topic }}</a></p>
  
  <p>Add a new entry:</p>
  <form action="{% url 'app_learning_logs:new_entry' topic.id %}" method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <button name="submit">Add entry</button>
  </form>
    
{% endblock content %}

project3/app_learning_logs/templates/app_learning_logs/new_topic.html
{% extends 'app_learning_logs/base.html' %}

{% block content %}
  <p>Add a new topic:</p>

  <form action="{% url 'app_learning_logs:new_topic' %}" method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <button name="submit">Add topic</button>
  </form>
    
{% endblock content %}
    

project3/app_learning_logs/templates/app_learning_logs/topic.html
{% extends 'app_learning_logs/base.html' %}
{% block content %}
    <p>Topic: {{ topic }}</p>
    <p>Entries:</p>
    <p> 
        <a href ="{% url 'app_learning_logs:new_entry' topic.id %}">Add new entry</a>
    </p>
    <ul>
    {% for entry in entries %}
        <li>
            <p>{{ entry.date_added | date:' M d, Y H:i' }}</p>
            <p>{{ entry.text | linebreaks }}</p>
        </li> 
    {% empty %} 
        <li> There are no entries for this topic yet. </li> 
    {% endfor %}
    </ul> 

{% endblock content %}

project3/app_learning_logs/templates/app_learning_logs/topics.html
{% extends 'app_learning_logs/base.html' %}
{% block content %}

  <p>Topics</p>

  <ul>
      {% for topic in topics %}
        <li>
          <a href="{% url 'app_learning_logs:topic' topic.id %}">{{ topic }}</a>
        </li>
      {% empty %}
        <li>No topics have been added yet.</li>
      {% endfor %}
  </ul>
  <a href="{% url 'app_learning_logs:new_topic' %}">Add a new topic</a>
  
{% endblock content %}